[db]
DATABASE_URL = "postgresql://postgres:N%40mikaz312@db.kknqpdhkcopfhjqiklne.supabase.co:5432/postgres?sslmode=require"
DB_TYPE = "postgresql"
DB_HOST = "db.qgchwhriueqriqrcepqw.supabase.co"
DB_PORT = 5432
DB_NAME = "postgres"
DB_USER = "postgres"
DB_PASSWORD = "N@mikaz312"

