[db]
DATABASE_URL = "postgresql://postgres.kknqpdhkcopfhjqiklne:N%40mikaz312@aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?sslmode=require"
DB_TYPE = "postgresql"
DB_HOST = "db.qgchwhriueqriqrcepqw.supabase.co"
DB_PORT = 6543
DB_NAME = "postgres"
DB_USER = "postgres"
DB_PASSWORD = "N@mikaz312"

